server:
  port: 8081

spring:
  # Multiple DataSource Configuration
  datasource:
    # 1. Primary DataSource - Auth DB
    auth:
      jdbc-url: jdbc:postgresql://localhost:5432/auth_service_db
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver
    # 2. Secondary DataSource - Shared Config DB
    shared:
      enabled: true
      jdbc-url: jdbc:postgresql://localhost:5432/shared_config_db
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

# Kafka Configuration for Auth Service
kafka:
  consumer:
    group-id: auth-service-group
    auto-offset-reset: earliest
    enable-auto-commit: true
    auto-commit-interval: 1000
  producer:
    acks: all
    retries: 3
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
