spring:
  application:
    name: menu-service

  # PostgreSQL Configuration for Menu Service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/menu_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  # Kafka Consumer Group for Menu Service
  kafka:
    consumer:
      group-id: menu-service-group

server:
  port: 8082

# Security configuration
restaurant:
  security:
    default-type: JWT
    jwt:
      cookie-name: auth_token
      enc:
        private-key: ${JWT_ENC_PRIVATE_KEY:}
      sig:
        public-key: ${JWT_SIG_PUBLIC_KEY:}
    endpoints:
      - path: /actuator/**
        type: PUBLIC
      - path: /api/menu/{id}
        type: PUBLIC
      - path: /api/menu/available
        type: PUBLIC
