# Order Service Configuration
spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Kafka configuration
kafka:
  consumer:
    group-id: order-service-group


# Redis cache
redis:
  host: localhost
  port: 6379



# Circuit breaker (optional - if using Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      menu-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    com.restaurant.orderservice.client: DEBUG