# Order Service Configuration
spring:
  application:
    name: order-service
  datasource:
    # 1. Primary DataSource - Order DB
    order:
      jdbc-url: jdbc:postgresql://localhost:5432/order_service_db
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 3
        minimum-idle: 1
    # 2. Secondary DataSource - Shared Config DB
    shared:
      enabled: true
      jdbc-url: jdbc:postgresql://localhost:5432/shared_config_db
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 2
        minimum-idle: 1

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Kafka configuration
kafka:
  consumer:
    group-id: order-service-group


# Redis cache
redis:
  host: localhost
  port: 6379



# Circuit breaker (optional - if using Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      menu-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    com.restaurant.orderservice.client: DEBUG

# Security configuration
restaurant:
  security:
    default-type: JWT
    jwt:
      cookie-name: auth_token
      enc:
        private-key: ${JWT_ENC_PRIVATE_KEY:}
      sig:
        public-key: ${JWT_SIG_PUBLIC_KEY:}
    endpoints:
      - path: /actuator/**
        type: PUBLIC
jwt:
  session-validation:
    feign:
      enabled: true
