# application.yml
spring:
  application:
    name: order-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: full
          menu-service:
            connect-timeout: 3000
            read-timeout: 3000

# Circuit breaker (optional - if using Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      menu-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    com.restaurant.orderservice.client: DEBUG