spring:
  application:
    name: profile-service

  # Multiple DataSource Configuration
  datasource:
    # 1. Primary DataSource - Profile DB
    profile:
      jdbc-url: jdbc:postgresql://localhost:5432/profile_service_db
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver
    # 2. Secondary DataSource - Shared Config DB
    shared:
      enabled: true
      jdbc-url: jdbc:postgresql://localhost:5432/shared_config_db
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver

  # Kafka Configuration for Profile Service (Consumer)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: profile-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 100

server:
  port: 8084


# Security configuration
restaurant:
  security:
    default-type: JWT
    jwt:
      cookie-name: auth_token
      enc:
        private-key: ${JWT_ENC_PRIVATE_KEY:}
      sig:
        public-key: ${JWT_SIG_PUBLIC_KEY:}
    endpoints:
      - path: /actuator/**
        type: PUBLIC
