spring:
  application:
    name: profile-service

  # PostgreSQL Configuration for Profile Service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/profile_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  # Kafka Configuration for Profile Service (Consumer)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: profile-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 100

server:
  port: 8084


# Security configuration
restaurant:
  security:
    default-type: JWT
    jwt:
      cookie-name: auth_token
      enc:
        private-key: ${JWT_ENC_PRIVATE_KEY:}
      sig:
        public-key: ${JWT_SIG_PUBLIC_KEY:}
    endpoints:
      - path: /actuator/**
        type: PUBLIC
