spring:
  application:
    name: reservation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/reservation_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Kafka Consumer Group for Reservation Service
  kafka:
    consumer:
      group-id: reservation-service-group

server:
  port: 8086

# Security configuration
restaurant:
  security:
    default-type: JWT
    jwt:
      cookie-name: auth_token
      enc:
        private-key: ${JWT_ENC_PRIVATE_KEY:}
      sig:
        public-key: ${JWT_SIG_PUBLIC_KEY:}
    endpoints:
      - path: /actuator/**
        type: PUBLIC
      - path: /api/reservations/guest
        type: PUBLIC
      - path: /api/reservations/availability
        type: PUBLIC
      - path: /api/reservations/confirmation/**
        type: PUBLIC


