spring:
  application:
    name: table-service

  # PostgreSQL Configuration for Table Service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/table_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  # Kafka Consumer Group for Table Service
  kafka:
    consumer:
      group-id: table-service-group

server:
  port: 8086

